### PR TITLE
Add max width to entity icons in tree

### LINKED ISSUE #109: Icons Don't scale
if you download svg files and use them as icons...
obraz
they don't scale down

I basicaly downloaded some svgs from game-icons and well that is how it looks

### PR DESCRIPTION
**Pull request by andersmmg**
## Description

Sets max width of tree item icons for entities in tree. This allows using larger scale svg icons without having to scale them just to use them in Pandora.

## Addressed issues

- closes #109

### CODE REVIEW

**Comment by andersmmg** [comment]
This basically fixes it, but probably needs work for editor scaling

**Comment by andersmmg** [comment]
Okay, this actually seems to work. Just multiplies the editor scale by 16 to calculate the icon scale. Tested with 75% scale and 125%

**Comment by bitbrain** [comment]
@andersmmg unfortunately, EditorInterface needs to be passed through manually, as it would break compatibility otherwise with Godot 4.1 and 4.0 (see failures)

**Review by bitbrain — CHANGES_REQUESTED** [review]
Pass through EditorInterface manually to remain backwards-compatible.

**Comment by bitbrain** [comment]
@andersmmg any update on this?

**Comment by andersmmg** [comment]
Sorry, haven't been working on this kind of stuff in a while. I think this should at least fix it to be more backwards compatible?

**Comment by bitbrain** [comment]
Seems to fail still:
```
ERROR: The object does not have any 'meta' values with the key 'PandoraEditorPlugin'.
   at: get_meta (core/object/object.cpp:924)
```
See: https://github.com/bitbrain/pandora/actions/runs/9361941184/job/25974226743?pr=165

**Comment by andersmmg** [comment]
That's odd, it works on my end. The meta value is set in "_enter_tree" of the plugin, so I'm not sure why a part of the plugin thinks it's not set. It's also odd that the issue doesn't show up until partway through the unit tests, I couldn't find anything specific about why it would fail when running the test_create_reference_array test specifically

**Comment by andersmmg** [comment]
This may work, and hopefully will pass the unit tests. I've been unable to run the tests locally, gdunit won't work for me

**Comment by bitbrain** [comment]
Hey, thanks for this!

**Review by bitbrain — APPROVED** [review]

**Pull request merged**
